spring:
  thymeleaf:
    cache: false
  main:
    show-banner: false
  datasource:
    url: jdbc:mysql://106.54.101.125:3306/MonkeyDocDB
    username: root
    password: monkeydoc123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 200
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext